[[types]]
    [types.match]
        type = "uint64"

    [types.replace]
        type = "int64"

[[types]]
    [types.match]
        type = "uint"

    [types.replace]
        type = "int"

[[types]]
    [types.match]
        type = "null.Uint64"
        nullable = true

    [types.replace]
        type = "null.Int64"

[[types]]
    [types.match]
        type = "int8"

    [types.replace]
        type = "int"

# ipa table
[[types]]
  [types.match]
    name = "type"
    type = "string"
    tables = ["ipa"]

  [types.replace]
    type = "enum.IpaType"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# ipa_version table
[[types]]
  [types.match]
    name = "ipa_type"
    type = "string"
    tables = ["ipa_version"]

  [types.replace]
    type = "enum.IpaType"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["ipa_version"]

  [types.replace]
    type = "datatype.IpaVersionBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# admin_dump_order table
[[types]]
  [types.match]
    name = "status"
    type = "string"
    tables = ["admin_dump_order"]

  [types.replace]
    type = "enum.AdminDumpOrderStatus"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']


# member_download_ipa_record table
[[types]]
  [types.match]
    name = "ipa_type"
    type = "string"
    tables = ["member_download_ipa_record"]

  [types.replace]
    type = "enum.IpaType"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']


# ipa_sign table
[[types]]
  [types.match]
    name = "status"
    type = "string"
    tables = ["ipa_sign"]

  [types.replace]
    type = "enum.IpaSignStatus"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# member_pay_order table
[[types]]
  [types.match]
    name = "status"
    type = "string"
    tables = ["member_pay_order"]

  [types.replace]
    type = "enum.MemberPayOrderStatus"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["member_pay_order"]

  [types.replace]
    type = "datatype.MemberPayOrderBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# member_pay_count table
[[types]]
  [types.match]
    name = "status"
    type = "string"
    tables = ["member_pay_count"]

  [types.replace]
    type = "enum.MemberPayCountStatus"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# member_pay_count table
[[types]]
  [types.match]
    name = "source"
    type = "string"
    tables = ["member_pay_count"]

  [types.replace]
    type = "enum.MemberPayCountSource"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# account table
[[types]]
  [types.match]
    name = "role"
    type = "string"
    tables = ["account"]

  [types.replace]
    type = "enum.AccountRole"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# certificate table
[[types]]
  [types.match]
    name = "source"
    type = "string"
    tables = ["certificate"]

  [types.replace]
    type = "enum.CertificateSource"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# certificate_v2 table
[[types]]
  [types.match]
    name = "source"
    type = "string"
    tables = ["certificate_v2"]

  [types.replace]
    type = "enum.CertificateSource"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["certificate_v2"]

  [types.replace]
    type = "datatype.CertificateBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']


# intall_app_cdkey_order table
[[types]]
  [types.match]
    name = "status"
    type = "string"
    tables = ["install_app_cdkey_order"]

  [types.replace]
    type = "enum.MemberPayOrderStatus"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# install_app_cdkey
[[types]]
  [types.match]
    name = "status"
    type = "string"
    tables = ["install_app_cdkey"]

  [types.replace]
    type = "enum.InstallAppCDKeyStatus"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# install_app_certificate table
[[types]]
  [types.match]
    name = "source"
    type = "string"
    tables = ["install_app_certificate"]

  [types.replace]
    type = "enum.CertificateSource"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["install_app_certificate"]

  [types.replace]
    type = "datatype.CertificateBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# member_device
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["member_device"]

  [types.replace]
    type = "datatype.MemberDeviceBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# memebr_pay_count_record table
[[types]]
  [types.match]
    name = "type"
    type = "string"
    tables = ["member_pay_count_record"]

  [types.replace]
    type = "enum.MemberPayCountRecordType"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["member_pay_count_record"]

  [types.replace]
    type = "datatype.MemberPayCountRecordBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# app_time_lock table
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["app_time_lock"]

  [types.replace]
    type = "datatype.AppTimeLockBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# app_source table
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["app_source"]

  [types.replace]
    type = "datatype.AppSourceBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# member_sign_ipa table
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["member_sign_ipa"]

  [types.replace]
    type = "datatype.MemberSignIpaBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# ipa_black table
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["ipa_black"]

  [types.replace]
    type = "datatype.IpaBlackBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# file
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["file"]

  [types.replace]
    type = "datatype.FileBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# dispense_count
[[types]]
  [types.match]
    name = "status"
    type = "string"
    tables = ["dispense_count"]

  [types.replace]
    type = "enum.DispenseCountStatus"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# dispense_count_record
[[types]]
  [types.match]
    name = "type"
    type = "string"
    tables = ["dispense_count_record"]

  [types.replace]
    type = "enum.DispenseCountRecordType"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/enum"']

# dumpapp_version
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["dumpapp_version"]

  [types.replace]
    type = "datatype.DumpappVersionBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

#  install_app_cdkey_order
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["install_app_cdkey_order"]

  [types.replace]
    type = "datatype.InstallAppCdkeyOrderBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# admin_config
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["admin_config_info"]

  [types.replace]
    type = "datatype.AdminConfigInfoBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# admin_auth_website
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["admin_auth_website"]

  [types.replace]
    type = "datatype.AdminAuthWebsiteBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']

# admin_auth_website
[[types]]
  [types.match]
    name = "biz_ext"
    type = "string"
    tables = ["certificate_device"]

  [types.replace]
    type = "datatype.CertificateDeviceBizExt"

  [types.imports]
    third_party = ['"dumpapp_server/pkg/common/datatype"']
