// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account              string
	Feedback             string
	Ipa                  string
	IpaVersion           string
	MemberDownloadNumber string
	MemberDownloadOrder  string
	MemberInvite         string
	MemberInviteCode     string
	MemberVip            string
	MemberVipOrder       string
	SearchRecordV2       string
}{
	Account:              "account",
	Feedback:             "feedback",
	Ipa:                  "ipa",
	IpaVersion:           "ipa_version",
	MemberDownloadNumber: "member_download_number",
	MemberDownloadOrder:  "member_download_order",
	MemberInvite:         "member_invite",
	MemberInviteCode:     "member_invite_code",
	MemberVip:            "member_vip",
	MemberVipOrder:       "member_vip_order",
	SearchRecordV2:       "search_record_v2",
}
