// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account                 string
	AdminDumpOrder          string
	Certificate             string
	CertificateDevice       string
	Feedback                string
	Ipa                     string
	IpaSign                 string
	IpaVersion              string
	MemberDevice            string
	MemberDownloadIpaRecord string
	MemberDownloadOrder     string
	MemberIDEncryption      string
	MemberInvite            string
	MemberInviteCode        string
	MemberPayCount          string
	MemberPayOrder          string
	SearchRecordV2          string
}{
	Account:                 "account",
	AdminDumpOrder:          "admin_dump_order",
	Certificate:             "certificate",
	CertificateDevice:       "certificate_device",
	Feedback:                "feedback",
	Ipa:                     "ipa",
	IpaSign:                 "ipa_sign",
	IpaVersion:              "ipa_version",
	MemberDevice:            "member_device",
	MemberDownloadIpaRecord: "member_download_ipa_record",
	MemberDownloadOrder:     "member_download_order",
	MemberIDEncryption:      "member_id_encryption",
	MemberInvite:            "member_invite",
	MemberInviteCode:        "member_invite_code",
	MemberPayCount:          "member_pay_count",
	MemberPayOrder:          "member_pay_order",
	SearchRecordV2:          "search_record_v2",
}
