// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account             string
	Ipa                 string
	IpaVersion          string
	MemberDownloadCount string
	MemberVip           string
	MemberVipOrder      string
	SearchRecordV2      string
}{
	Account:             "account",
	Ipa:                 "ipa",
	IpaVersion:          "ipa_version",
	MemberDownloadCount: "member_download_count",
	MemberVip:           "member_vip",
	MemberVipOrder:      "member_vip_order",
	SearchRecordV2:      "search_record_v2",
}
