// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DailyFreeRecord is an object representing the database table.
type DailyFreeRecord struct {
	ID         int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	MemberID   int64     `boil:"member_id" json:"member_id" toml:"member_id" yaml:"member_id"`
	IpaID      int64     `boil:"ipa_id" json:"ipa_id" toml:"ipa_id" yaml:"ipa_id"`
	IpaVersion string    `boil:"ipa_version" json:"ipa_version" toml:"ipa_version" yaml:"ipa_version"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *dailyFreeRecordR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dailyFreeRecordL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DailyFreeRecordColumns = struct {
	ID         string
	MemberID   string
	IpaID      string
	IpaVersion string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	MemberID:   "member_id",
	IpaID:      "ipa_id",
	IpaVersion: "ipa_version",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var DailyFreeRecordTableColumns = struct {
	ID         string
	MemberID   string
	IpaID      string
	IpaVersion string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "daily_free_record.id",
	MemberID:   "daily_free_record.member_id",
	IpaID:      "daily_free_record.ipa_id",
	IpaVersion: "daily_free_record.ipa_version",
	CreatedAt:  "daily_free_record.created_at",
	UpdatedAt:  "daily_free_record.updated_at",
}

// Generated where

var DailyFreeRecordWhere = struct {
	ID         whereHelperint64
	MemberID   whereHelperint64
	IpaID      whereHelperint64
	IpaVersion whereHelperstring
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
}{
	ID:         whereHelperint64{field: "`daily_free_record`.`id`"},
	MemberID:   whereHelperint64{field: "`daily_free_record`.`member_id`"},
	IpaID:      whereHelperint64{field: "`daily_free_record`.`ipa_id`"},
	IpaVersion: whereHelperstring{field: "`daily_free_record`.`ipa_version`"},
	CreatedAt:  whereHelpertime_Time{field: "`daily_free_record`.`created_at`"},
	UpdatedAt:  whereHelpertime_Time{field: "`daily_free_record`.`updated_at`"},
}

// DailyFreeRecordRels is where relationship names are stored.
var DailyFreeRecordRels = struct {
}{}

// dailyFreeRecordR is where relationships are stored.
type dailyFreeRecordR struct {
}

// NewStruct creates a new relationship struct
func (*dailyFreeRecordR) NewStruct() *dailyFreeRecordR {
	return &dailyFreeRecordR{}
}

// dailyFreeRecordL is where Load methods for each relationship are stored.
type dailyFreeRecordL struct{}

var (
	dailyFreeRecordAllColumns            = []string{"id", "member_id", "ipa_id", "ipa_version", "created_at", "updated_at"}
	dailyFreeRecordColumnsWithoutDefault = []string{"member_id", "ipa_id", "ipa_version"}
	dailyFreeRecordColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	dailyFreeRecordPrimaryKeyColumns     = []string{"id"}
	dailyFreeRecordGeneratedColumns      = []string{}
)

type (
	// DailyFreeRecordSlice is an alias for a slice of pointers to DailyFreeRecord.
	// This should almost always be used instead of []DailyFreeRecord.
	DailyFreeRecordSlice []*DailyFreeRecord
	// DailyFreeRecordHook is the signature for custom DailyFreeRecord hook methods
	DailyFreeRecordHook func(context.Context, boil.ContextExecutor, *DailyFreeRecord) error

	dailyFreeRecordQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dailyFreeRecordType                 = reflect.TypeOf(&DailyFreeRecord{})
	dailyFreeRecordMapping              = queries.MakeStructMapping(dailyFreeRecordType)
	dailyFreeRecordPrimaryKeyMapping, _ = queries.BindMapping(dailyFreeRecordType, dailyFreeRecordMapping, dailyFreeRecordPrimaryKeyColumns)
	dailyFreeRecordInsertCacheMut       sync.RWMutex
	dailyFreeRecordInsertCache          = make(map[string]insertCache)
	dailyFreeRecordUpdateCacheMut       sync.RWMutex
	dailyFreeRecordUpdateCache          = make(map[string]updateCache)
	dailyFreeRecordUpsertCacheMut       sync.RWMutex
	dailyFreeRecordUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dailyFreeRecordAfterSelectHooks []DailyFreeRecordHook

var dailyFreeRecordBeforeInsertHooks []DailyFreeRecordHook
var dailyFreeRecordAfterInsertHooks []DailyFreeRecordHook

var dailyFreeRecordBeforeUpdateHooks []DailyFreeRecordHook
var dailyFreeRecordAfterUpdateHooks []DailyFreeRecordHook

var dailyFreeRecordBeforeDeleteHooks []DailyFreeRecordHook
var dailyFreeRecordAfterDeleteHooks []DailyFreeRecordHook

var dailyFreeRecordBeforeUpsertHooks []DailyFreeRecordHook
var dailyFreeRecordAfterUpsertHooks []DailyFreeRecordHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DailyFreeRecord) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DailyFreeRecord) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DailyFreeRecord) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DailyFreeRecord) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DailyFreeRecord) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DailyFreeRecord) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DailyFreeRecord) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DailyFreeRecord) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DailyFreeRecord) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dailyFreeRecordAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDailyFreeRecordHook registers your hook function for all future operations.
func AddDailyFreeRecordHook(hookPoint boil.HookPoint, dailyFreeRecordHook DailyFreeRecordHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dailyFreeRecordAfterSelectHooks = append(dailyFreeRecordAfterSelectHooks, dailyFreeRecordHook)
	case boil.BeforeInsertHook:
		dailyFreeRecordBeforeInsertHooks = append(dailyFreeRecordBeforeInsertHooks, dailyFreeRecordHook)
	case boil.AfterInsertHook:
		dailyFreeRecordAfterInsertHooks = append(dailyFreeRecordAfterInsertHooks, dailyFreeRecordHook)
	case boil.BeforeUpdateHook:
		dailyFreeRecordBeforeUpdateHooks = append(dailyFreeRecordBeforeUpdateHooks, dailyFreeRecordHook)
	case boil.AfterUpdateHook:
		dailyFreeRecordAfterUpdateHooks = append(dailyFreeRecordAfterUpdateHooks, dailyFreeRecordHook)
	case boil.BeforeDeleteHook:
		dailyFreeRecordBeforeDeleteHooks = append(dailyFreeRecordBeforeDeleteHooks, dailyFreeRecordHook)
	case boil.AfterDeleteHook:
		dailyFreeRecordAfterDeleteHooks = append(dailyFreeRecordAfterDeleteHooks, dailyFreeRecordHook)
	case boil.BeforeUpsertHook:
		dailyFreeRecordBeforeUpsertHooks = append(dailyFreeRecordBeforeUpsertHooks, dailyFreeRecordHook)
	case boil.AfterUpsertHook:
		dailyFreeRecordAfterUpsertHooks = append(dailyFreeRecordAfterUpsertHooks, dailyFreeRecordHook)
	}
}

// One returns a single dailyFreeRecord record from the query.
func (q dailyFreeRecordQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DailyFreeRecord, error) {
	o := &DailyFreeRecord{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for daily_free_record")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DailyFreeRecord records from the query.
func (q dailyFreeRecordQuery) All(ctx context.Context, exec boil.ContextExecutor) (DailyFreeRecordSlice, error) {
	var o []*DailyFreeRecord

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DailyFreeRecord slice")
	}

	if len(dailyFreeRecordAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DailyFreeRecord records in the query.
func (q dailyFreeRecordQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count daily_free_record rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dailyFreeRecordQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if daily_free_record exists")
	}

	return count > 0, nil
}

// DailyFreeRecords retrieves all the records using an executor.
func DailyFreeRecords(mods ...qm.QueryMod) dailyFreeRecordQuery {
	mods = append(mods, qm.From("`daily_free_record`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`daily_free_record`.*"})
	}

	return dailyFreeRecordQuery{q}
}

// FindDailyFreeRecord retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDailyFreeRecord(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*DailyFreeRecord, error) {
	dailyFreeRecordObj := &DailyFreeRecord{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `daily_free_record` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dailyFreeRecordObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from daily_free_record")
	}

	if err = dailyFreeRecordObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dailyFreeRecordObj, err
	}

	return dailyFreeRecordObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DailyFreeRecord) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no daily_free_record provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dailyFreeRecordColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dailyFreeRecordInsertCacheMut.RLock()
	cache, cached := dailyFreeRecordInsertCache[key]
	dailyFreeRecordInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dailyFreeRecordAllColumns,
			dailyFreeRecordColumnsWithDefault,
			dailyFreeRecordColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dailyFreeRecordType, dailyFreeRecordMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dailyFreeRecordType, dailyFreeRecordMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `daily_free_record` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `daily_free_record` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `daily_free_record` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dailyFreeRecordPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into daily_free_record")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dailyFreeRecordMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for daily_free_record")
	}

CacheNoHooks:
	if !cached {
		dailyFreeRecordInsertCacheMut.Lock()
		dailyFreeRecordInsertCache[key] = cache
		dailyFreeRecordInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DailyFreeRecord.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DailyFreeRecord) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dailyFreeRecordUpdateCacheMut.RLock()
	cache, cached := dailyFreeRecordUpdateCache[key]
	dailyFreeRecordUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dailyFreeRecordAllColumns,
			dailyFreeRecordPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update daily_free_record, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `daily_free_record` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dailyFreeRecordPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dailyFreeRecordType, dailyFreeRecordMapping, append(wl, dailyFreeRecordPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update daily_free_record row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for daily_free_record")
	}

	if !cached {
		dailyFreeRecordUpdateCacheMut.Lock()
		dailyFreeRecordUpdateCache[key] = cache
		dailyFreeRecordUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dailyFreeRecordQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for daily_free_record")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for daily_free_record")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DailyFreeRecordSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dailyFreeRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `daily_free_record` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dailyFreeRecordPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in dailyFreeRecord slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all dailyFreeRecord")
	}
	return rowsAff, nil
}

var mySQLDailyFreeRecordUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DailyFreeRecord) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no daily_free_record provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dailyFreeRecordColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDailyFreeRecordUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dailyFreeRecordUpsertCacheMut.RLock()
	cache, cached := dailyFreeRecordUpsertCache[key]
	dailyFreeRecordUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			dailyFreeRecordAllColumns,
			dailyFreeRecordColumnsWithDefault,
			dailyFreeRecordColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dailyFreeRecordAllColumns,
			dailyFreeRecordPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert daily_free_record, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`daily_free_record`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `daily_free_record` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dailyFreeRecordType, dailyFreeRecordMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dailyFreeRecordType, dailyFreeRecordMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for daily_free_record")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dailyFreeRecordMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dailyFreeRecordType, dailyFreeRecordMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for daily_free_record")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for daily_free_record")
	}

CacheNoHooks:
	if !cached {
		dailyFreeRecordUpsertCacheMut.Lock()
		dailyFreeRecordUpsertCache[key] = cache
		dailyFreeRecordUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DailyFreeRecord record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DailyFreeRecord) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DailyFreeRecord provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dailyFreeRecordPrimaryKeyMapping)
	sql := "DELETE FROM `daily_free_record` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from daily_free_record")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for daily_free_record")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dailyFreeRecordQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no dailyFreeRecordQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from daily_free_record")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for daily_free_record")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DailyFreeRecordSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dailyFreeRecordBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dailyFreeRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `daily_free_record` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dailyFreeRecordPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from dailyFreeRecord slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for daily_free_record")
	}

	if len(dailyFreeRecordAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DailyFreeRecord) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDailyFreeRecord(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DailyFreeRecordSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DailyFreeRecordSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dailyFreeRecordPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `daily_free_record`.* FROM `daily_free_record` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dailyFreeRecordPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DailyFreeRecordSlice")
	}

	*o = slice

	return nil
}

// DailyFreeRecordExists checks if the DailyFreeRecord row exists.
func DailyFreeRecordExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `daily_free_record` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if daily_free_record exists")
	}

	return exists, nil
}

// Exists checks if the DailyFreeRecord row exists.
func (o *DailyFreeRecord) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DailyFreeRecordExists(ctx, exec, o.ID)
}
