// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"dumpapp_server/pkg/common/enum"
	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DispenseCount is an object representing the database table.
type DispenseCount struct {
	ID       int64                    `boil:"id" json:"id" toml:"id" yaml:"id"`
	MemberID int64                    `boil:"member_id" json:"member_id" toml:"member_id" yaml:"member_id"`
	Status   enum.DispenseCountStatus `boil:"status" json:"status" toml:"status" yaml:"status"`
	// ????
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// ????
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *dispenseCountR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dispenseCountL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DispenseCountColumns = struct {
	ID        string
	MemberID  string
	Status    string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	MemberID:  "member_id",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var DispenseCountTableColumns = struct {
	ID        string
	MemberID  string
	Status    string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "dispense_count.id",
	MemberID:  "dispense_count.member_id",
	Status:    "dispense_count.status",
	CreatedAt: "dispense_count.created_at",
	UpdatedAt: "dispense_count.updated_at",
}

// Generated where

type whereHelperenum_DispenseCountStatus struct{ field string }

func (w whereHelperenum_DispenseCountStatus) EQ(x enum.DispenseCountStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperenum_DispenseCountStatus) NEQ(x enum.DispenseCountStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperenum_DispenseCountStatus) LT(x enum.DispenseCountStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperenum_DispenseCountStatus) LTE(x enum.DispenseCountStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperenum_DispenseCountStatus) GT(x enum.DispenseCountStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperenum_DispenseCountStatus) GTE(x enum.DispenseCountStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var DispenseCountWhere = struct {
	ID        whereHelperint64
	MemberID  whereHelperint64
	Status    whereHelperenum_DispenseCountStatus
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "`dispense_count`.`id`"},
	MemberID:  whereHelperint64{field: "`dispense_count`.`member_id`"},
	Status:    whereHelperenum_DispenseCountStatus{field: "`dispense_count`.`status`"},
	CreatedAt: whereHelpertime_Time{field: "`dispense_count`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`dispense_count`.`updated_at`"},
}

// DispenseCountRels is where relationship names are stored.
var DispenseCountRels = struct {
}{}

// dispenseCountR is where relationships are stored.
type dispenseCountR struct {
}

// NewStruct creates a new relationship struct
func (*dispenseCountR) NewStruct() *dispenseCountR {
	return &dispenseCountR{}
}

// dispenseCountL is where Load methods for each relationship are stored.
type dispenseCountL struct{}

var (
	dispenseCountAllColumns            = []string{"id", "member_id", "status", "created_at", "updated_at"}
	dispenseCountColumnsWithoutDefault = []string{"member_id", "status"}
	dispenseCountColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	dispenseCountPrimaryKeyColumns     = []string{"id"}
	dispenseCountGeneratedColumns      = []string{}
)

type (
	// DispenseCountSlice is an alias for a slice of pointers to DispenseCount.
	// This should almost always be used instead of []DispenseCount.
	DispenseCountSlice []*DispenseCount
	// DispenseCountHook is the signature for custom DispenseCount hook methods
	DispenseCountHook func(context.Context, boil.ContextExecutor, *DispenseCount) error

	dispenseCountQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dispenseCountType                 = reflect.TypeOf(&DispenseCount{})
	dispenseCountMapping              = queries.MakeStructMapping(dispenseCountType)
	dispenseCountPrimaryKeyMapping, _ = queries.BindMapping(dispenseCountType, dispenseCountMapping, dispenseCountPrimaryKeyColumns)
	dispenseCountInsertCacheMut       sync.RWMutex
	dispenseCountInsertCache          = make(map[string]insertCache)
	dispenseCountUpdateCacheMut       sync.RWMutex
	dispenseCountUpdateCache          = make(map[string]updateCache)
	dispenseCountUpsertCacheMut       sync.RWMutex
	dispenseCountUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var dispenseCountAfterSelectHooks []DispenseCountHook

var dispenseCountBeforeInsertHooks []DispenseCountHook
var dispenseCountAfterInsertHooks []DispenseCountHook

var dispenseCountBeforeUpdateHooks []DispenseCountHook
var dispenseCountAfterUpdateHooks []DispenseCountHook

var dispenseCountBeforeDeleteHooks []DispenseCountHook
var dispenseCountAfterDeleteHooks []DispenseCountHook

var dispenseCountBeforeUpsertHooks []DispenseCountHook
var dispenseCountAfterUpsertHooks []DispenseCountHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DispenseCount) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DispenseCount) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DispenseCount) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DispenseCount) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DispenseCount) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DispenseCount) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DispenseCount) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DispenseCount) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DispenseCount) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range dispenseCountAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDispenseCountHook registers your hook function for all future operations.
func AddDispenseCountHook(hookPoint boil.HookPoint, dispenseCountHook DispenseCountHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		dispenseCountAfterSelectHooks = append(dispenseCountAfterSelectHooks, dispenseCountHook)
	case boil.BeforeInsertHook:
		dispenseCountBeforeInsertHooks = append(dispenseCountBeforeInsertHooks, dispenseCountHook)
	case boil.AfterInsertHook:
		dispenseCountAfterInsertHooks = append(dispenseCountAfterInsertHooks, dispenseCountHook)
	case boil.BeforeUpdateHook:
		dispenseCountBeforeUpdateHooks = append(dispenseCountBeforeUpdateHooks, dispenseCountHook)
	case boil.AfterUpdateHook:
		dispenseCountAfterUpdateHooks = append(dispenseCountAfterUpdateHooks, dispenseCountHook)
	case boil.BeforeDeleteHook:
		dispenseCountBeforeDeleteHooks = append(dispenseCountBeforeDeleteHooks, dispenseCountHook)
	case boil.AfterDeleteHook:
		dispenseCountAfterDeleteHooks = append(dispenseCountAfterDeleteHooks, dispenseCountHook)
	case boil.BeforeUpsertHook:
		dispenseCountBeforeUpsertHooks = append(dispenseCountBeforeUpsertHooks, dispenseCountHook)
	case boil.AfterUpsertHook:
		dispenseCountAfterUpsertHooks = append(dispenseCountAfterUpsertHooks, dispenseCountHook)
	}
}

// One returns a single dispenseCount record from the query.
func (q dispenseCountQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DispenseCount, error) {
	o := &DispenseCount{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for dispense_count")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DispenseCount records from the query.
func (q dispenseCountQuery) All(ctx context.Context, exec boil.ContextExecutor) (DispenseCountSlice, error) {
	var o []*DispenseCount

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DispenseCount slice")
	}

	if len(dispenseCountAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DispenseCount records in the query.
func (q dispenseCountQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count dispense_count rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dispenseCountQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if dispense_count exists")
	}

	return count > 0, nil
}

// DispenseCounts retrieves all the records using an executor.
func DispenseCounts(mods ...qm.QueryMod) dispenseCountQuery {
	mods = append(mods, qm.From("`dispense_count`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`dispense_count`.*"})
	}

	return dispenseCountQuery{q}
}

// FindDispenseCount retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDispenseCount(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*DispenseCount, error) {
	dispenseCountObj := &DispenseCount{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `dispense_count` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, dispenseCountObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from dispense_count")
	}

	if err = dispenseCountObj.doAfterSelectHooks(ctx, exec); err != nil {
		return dispenseCountObj, err
	}

	return dispenseCountObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DispenseCount) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no dispense_count provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dispenseCountColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dispenseCountInsertCacheMut.RLock()
	cache, cached := dispenseCountInsertCache[key]
	dispenseCountInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dispenseCountAllColumns,
			dispenseCountColumnsWithDefault,
			dispenseCountColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dispenseCountType, dispenseCountMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dispenseCountType, dispenseCountMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `dispense_count` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `dispense_count` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `dispense_count` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dispenseCountPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into dispense_count")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dispenseCountMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for dispense_count")
	}

CacheNoHooks:
	if !cached {
		dispenseCountInsertCacheMut.Lock()
		dispenseCountInsertCache[key] = cache
		dispenseCountInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DispenseCount.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DispenseCount) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	dispenseCountUpdateCacheMut.RLock()
	cache, cached := dispenseCountUpdateCache[key]
	dispenseCountUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dispenseCountAllColumns,
			dispenseCountPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update dispense_count, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `dispense_count` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dispenseCountPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dispenseCountType, dispenseCountMapping, append(wl, dispenseCountPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update dispense_count row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for dispense_count")
	}

	if !cached {
		dispenseCountUpdateCacheMut.Lock()
		dispenseCountUpdateCache[key] = cache
		dispenseCountUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q dispenseCountQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for dispense_count")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for dispense_count")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DispenseCountSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dispenseCountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `dispense_count` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dispenseCountPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in dispenseCount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all dispenseCount")
	}
	return rowsAff, nil
}

var mySQLDispenseCountUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DispenseCount) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no dispense_count provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(dispenseCountColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDispenseCountUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dispenseCountUpsertCacheMut.RLock()
	cache, cached := dispenseCountUpsertCache[key]
	dispenseCountUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			dispenseCountAllColumns,
			dispenseCountColumnsWithDefault,
			dispenseCountColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dispenseCountAllColumns,
			dispenseCountPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert dispense_count, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`dispense_count`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `dispense_count` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dispenseCountType, dispenseCountMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dispenseCountType, dispenseCountMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for dispense_count")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == dispenseCountMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dispenseCountType, dispenseCountMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for dispense_count")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for dispense_count")
	}

CacheNoHooks:
	if !cached {
		dispenseCountUpsertCacheMut.Lock()
		dispenseCountUpsertCache[key] = cache
		dispenseCountUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DispenseCount record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DispenseCount) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DispenseCount provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dispenseCountPrimaryKeyMapping)
	sql := "DELETE FROM `dispense_count` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from dispense_count")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for dispense_count")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q dispenseCountQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no dispenseCountQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from dispense_count")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for dispense_count")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DispenseCountSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(dispenseCountBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dispenseCountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `dispense_count` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dispenseCountPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from dispenseCount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for dispense_count")
	}

	if len(dispenseCountAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DispenseCount) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDispenseCount(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DispenseCountSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DispenseCountSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dispenseCountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `dispense_count`.* FROM `dispense_count` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dispenseCountPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DispenseCountSlice")
	}

	*o = slice

	return nil
}

// DispenseCountExists checks if the DispenseCount row exists.
func DispenseCountExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `dispense_count` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if dispense_count exists")
	}

	return exists, nil
}

// Exists checks if the DispenseCount row exists.
func (o *DispenseCount) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DispenseCountExists(ctx, exec, o.ID)
}
