// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MemberIDEncryption is an object representing the database table.
type MemberIDEncryption struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	MemberID  int64     `boil:"member_id" json:"member_id" toml:"member_id" yaml:"member_id"`
	Code      string    `boil:"code" json:"code" toml:"code" yaml:"code"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *memberIDEncryptionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L memberIDEncryptionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MemberIDEncryptionColumns = struct {
	ID        string
	MemberID  string
	Code      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	MemberID:  "member_id",
	Code:      "code",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var MemberIDEncryptionTableColumns = struct {
	ID        string
	MemberID  string
	Code      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "member_id_encryption.id",
	MemberID:  "member_id_encryption.member_id",
	Code:      "member_id_encryption.code",
	CreatedAt: "member_id_encryption.created_at",
	UpdatedAt: "member_id_encryption.updated_at",
}

// Generated where

var MemberIDEncryptionWhere = struct {
	ID        whereHelperint64
	MemberID  whereHelperint64
	Code      whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "`member_id_encryption`.`id`"},
	MemberID:  whereHelperint64{field: "`member_id_encryption`.`member_id`"},
	Code:      whereHelperstring{field: "`member_id_encryption`.`code`"},
	CreatedAt: whereHelpertime_Time{field: "`member_id_encryption`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`member_id_encryption`.`updated_at`"},
}

// MemberIDEncryptionRels is where relationship names are stored.
var MemberIDEncryptionRels = struct {
}{}

// memberIDEncryptionR is where relationships are stored.
type memberIDEncryptionR struct {
}

// NewStruct creates a new relationship struct
func (*memberIDEncryptionR) NewStruct() *memberIDEncryptionR {
	return &memberIDEncryptionR{}
}

// memberIDEncryptionL is where Load methods for each relationship are stored.
type memberIDEncryptionL struct{}

var (
	memberIDEncryptionAllColumns            = []string{"id", "member_id", "code", "created_at", "updated_at"}
	memberIDEncryptionColumnsWithoutDefault = []string{"member_id", "code"}
	memberIDEncryptionColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	memberIDEncryptionPrimaryKeyColumns     = []string{"id"}
	memberIDEncryptionGeneratedColumns      = []string{}
)

type (
	// MemberIDEncryptionSlice is an alias for a slice of pointers to MemberIDEncryption.
	// This should almost always be used instead of []MemberIDEncryption.
	MemberIDEncryptionSlice []*MemberIDEncryption
	// MemberIDEncryptionHook is the signature for custom MemberIDEncryption hook methods
	MemberIDEncryptionHook func(context.Context, boil.ContextExecutor, *MemberIDEncryption) error

	memberIDEncryptionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	memberIDEncryptionType                 = reflect.TypeOf(&MemberIDEncryption{})
	memberIDEncryptionMapping              = queries.MakeStructMapping(memberIDEncryptionType)
	memberIDEncryptionPrimaryKeyMapping, _ = queries.BindMapping(memberIDEncryptionType, memberIDEncryptionMapping, memberIDEncryptionPrimaryKeyColumns)
	memberIDEncryptionInsertCacheMut       sync.RWMutex
	memberIDEncryptionInsertCache          = make(map[string]insertCache)
	memberIDEncryptionUpdateCacheMut       sync.RWMutex
	memberIDEncryptionUpdateCache          = make(map[string]updateCache)
	memberIDEncryptionUpsertCacheMut       sync.RWMutex
	memberIDEncryptionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var memberIDEncryptionAfterSelectHooks []MemberIDEncryptionHook

var memberIDEncryptionBeforeInsertHooks []MemberIDEncryptionHook
var memberIDEncryptionAfterInsertHooks []MemberIDEncryptionHook

var memberIDEncryptionBeforeUpdateHooks []MemberIDEncryptionHook
var memberIDEncryptionAfterUpdateHooks []MemberIDEncryptionHook

var memberIDEncryptionBeforeDeleteHooks []MemberIDEncryptionHook
var memberIDEncryptionAfterDeleteHooks []MemberIDEncryptionHook

var memberIDEncryptionBeforeUpsertHooks []MemberIDEncryptionHook
var memberIDEncryptionAfterUpsertHooks []MemberIDEncryptionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MemberIDEncryption) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MemberIDEncryption) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MemberIDEncryption) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MemberIDEncryption) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MemberIDEncryption) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MemberIDEncryption) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MemberIDEncryption) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MemberIDEncryption) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MemberIDEncryption) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range memberIDEncryptionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMemberIDEncryptionHook registers your hook function for all future operations.
func AddMemberIDEncryptionHook(hookPoint boil.HookPoint, memberIDEncryptionHook MemberIDEncryptionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		memberIDEncryptionAfterSelectHooks = append(memberIDEncryptionAfterSelectHooks, memberIDEncryptionHook)
	case boil.BeforeInsertHook:
		memberIDEncryptionBeforeInsertHooks = append(memberIDEncryptionBeforeInsertHooks, memberIDEncryptionHook)
	case boil.AfterInsertHook:
		memberIDEncryptionAfterInsertHooks = append(memberIDEncryptionAfterInsertHooks, memberIDEncryptionHook)
	case boil.BeforeUpdateHook:
		memberIDEncryptionBeforeUpdateHooks = append(memberIDEncryptionBeforeUpdateHooks, memberIDEncryptionHook)
	case boil.AfterUpdateHook:
		memberIDEncryptionAfterUpdateHooks = append(memberIDEncryptionAfterUpdateHooks, memberIDEncryptionHook)
	case boil.BeforeDeleteHook:
		memberIDEncryptionBeforeDeleteHooks = append(memberIDEncryptionBeforeDeleteHooks, memberIDEncryptionHook)
	case boil.AfterDeleteHook:
		memberIDEncryptionAfterDeleteHooks = append(memberIDEncryptionAfterDeleteHooks, memberIDEncryptionHook)
	case boil.BeforeUpsertHook:
		memberIDEncryptionBeforeUpsertHooks = append(memberIDEncryptionBeforeUpsertHooks, memberIDEncryptionHook)
	case boil.AfterUpsertHook:
		memberIDEncryptionAfterUpsertHooks = append(memberIDEncryptionAfterUpsertHooks, memberIDEncryptionHook)
	}
}

// One returns a single memberIDEncryption record from the query.
func (q memberIDEncryptionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MemberIDEncryption, error) {
	o := &MemberIDEncryption{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for member_id_encryption")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MemberIDEncryption records from the query.
func (q memberIDEncryptionQuery) All(ctx context.Context, exec boil.ContextExecutor) (MemberIDEncryptionSlice, error) {
	var o []*MemberIDEncryption

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MemberIDEncryption slice")
	}

	if len(memberIDEncryptionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MemberIDEncryption records in the query.
func (q memberIDEncryptionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count member_id_encryption rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q memberIDEncryptionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if member_id_encryption exists")
	}

	return count > 0, nil
}

// MemberIDEncryptions retrieves all the records using an executor.
func MemberIDEncryptions(mods ...qm.QueryMod) memberIDEncryptionQuery {
	mods = append(mods, qm.From("`member_id_encryption`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`member_id_encryption`.*"})
	}

	return memberIDEncryptionQuery{q}
}

// FindMemberIDEncryption retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMemberIDEncryption(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MemberIDEncryption, error) {
	memberIDEncryptionObj := &MemberIDEncryption{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `member_id_encryption` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, memberIDEncryptionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from member_id_encryption")
	}

	if err = memberIDEncryptionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return memberIDEncryptionObj, err
	}

	return memberIDEncryptionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MemberIDEncryption) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no member_id_encryption provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(memberIDEncryptionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	memberIDEncryptionInsertCacheMut.RLock()
	cache, cached := memberIDEncryptionInsertCache[key]
	memberIDEncryptionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			memberIDEncryptionAllColumns,
			memberIDEncryptionColumnsWithDefault,
			memberIDEncryptionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(memberIDEncryptionType, memberIDEncryptionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(memberIDEncryptionType, memberIDEncryptionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `member_id_encryption` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `member_id_encryption` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `member_id_encryption` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, memberIDEncryptionPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into member_id_encryption")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == memberIDEncryptionMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for member_id_encryption")
	}

CacheNoHooks:
	if !cached {
		memberIDEncryptionInsertCacheMut.Lock()
		memberIDEncryptionInsertCache[key] = cache
		memberIDEncryptionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MemberIDEncryption.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MemberIDEncryption) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	memberIDEncryptionUpdateCacheMut.RLock()
	cache, cached := memberIDEncryptionUpdateCache[key]
	memberIDEncryptionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			memberIDEncryptionAllColumns,
			memberIDEncryptionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update member_id_encryption, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `member_id_encryption` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, memberIDEncryptionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(memberIDEncryptionType, memberIDEncryptionMapping, append(wl, memberIDEncryptionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update member_id_encryption row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for member_id_encryption")
	}

	if !cached {
		memberIDEncryptionUpdateCacheMut.Lock()
		memberIDEncryptionUpdateCache[key] = cache
		memberIDEncryptionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q memberIDEncryptionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for member_id_encryption")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for member_id_encryption")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MemberIDEncryptionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), memberIDEncryptionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `member_id_encryption` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, memberIDEncryptionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in memberIDEncryption slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all memberIDEncryption")
	}
	return rowsAff, nil
}

var mySQLMemberIDEncryptionUniqueColumns = []string{
	"id",
	"member_id",
	"code",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MemberIDEncryption) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no member_id_encryption provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(memberIDEncryptionColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLMemberIDEncryptionUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	memberIDEncryptionUpsertCacheMut.RLock()
	cache, cached := memberIDEncryptionUpsertCache[key]
	memberIDEncryptionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			memberIDEncryptionAllColumns,
			memberIDEncryptionColumnsWithDefault,
			memberIDEncryptionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			memberIDEncryptionAllColumns,
			memberIDEncryptionPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert member_id_encryption, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`member_id_encryption`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `member_id_encryption` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(memberIDEncryptionType, memberIDEncryptionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(memberIDEncryptionType, memberIDEncryptionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for member_id_encryption")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == memberIDEncryptionMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(memberIDEncryptionType, memberIDEncryptionMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for member_id_encryption")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for member_id_encryption")
	}

CacheNoHooks:
	if !cached {
		memberIDEncryptionUpsertCacheMut.Lock()
		memberIDEncryptionUpsertCache[key] = cache
		memberIDEncryptionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MemberIDEncryption record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MemberIDEncryption) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MemberIDEncryption provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), memberIDEncryptionPrimaryKeyMapping)
	sql := "DELETE FROM `member_id_encryption` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from member_id_encryption")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for member_id_encryption")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q memberIDEncryptionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no memberIDEncryptionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from member_id_encryption")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for member_id_encryption")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MemberIDEncryptionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(memberIDEncryptionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), memberIDEncryptionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `member_id_encryption` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, memberIDEncryptionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from memberIDEncryption slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for member_id_encryption")
	}

	if len(memberIDEncryptionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MemberIDEncryption) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMemberIDEncryption(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MemberIDEncryptionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MemberIDEncryptionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), memberIDEncryptionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `member_id_encryption`.* FROM `member_id_encryption` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, memberIDEncryptionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MemberIDEncryptionSlice")
	}

	*o = slice

	return nil
}

// MemberIDEncryptionExists checks if the MemberIDEncryption row exists.
func MemberIDEncryptionExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `member_id_encryption` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if member_id_encryption exists")
	}

	return exists, nil
}

// Exists checks if the MemberIDEncryption row exists.
func (o *MemberIDEncryption) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MemberIDEncryptionExists(ctx, exec, o.ID)
}
