// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SearchRecordV2 is an object representing the database table.
type SearchRecordV2 struct {
	ID        int64       `boil:"id" json:"id,string" toml:"id" yaml:"id"`
	MemberID  int64       `boil:"member_id" json:"member_id" toml:"member_id" yaml:"member_id"`
	IpaID     int64       `boil:"ipa_id" json:"ipa_id" toml:"ipa_id" yaml:"ipa_id"`
	Name      string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Version   null.String `boil:"version" json:"version,omitempty" toml:"version" yaml:"version,omitempty"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *searchRecordV2R `boil:"-" json:"-" toml:"-" yaml:"-"`
	L searchRecordV2L  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SearchRecordV2Columns = struct {
	ID        string
	MemberID  string
	IpaID     string
	Name      string
	Version   string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	MemberID:  "member_id",
	IpaID:     "ipa_id",
	Name:      "name",
	Version:   "version",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

var SearchRecordV2Where = struct {
	ID        whereHelperint64
	MemberID  whereHelperint64
	IpaID     whereHelperint64
	Name      whereHelperstring
	Version   whereHelpernull_String
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "`search_record_v2`.`id`"},
	MemberID:  whereHelperint64{field: "`search_record_v2`.`member_id`"},
	IpaID:     whereHelperint64{field: "`search_record_v2`.`ipa_id`"},
	Name:      whereHelperstring{field: "`search_record_v2`.`name`"},
	Version:   whereHelpernull_String{field: "`search_record_v2`.`version`"},
	CreatedAt: whereHelpertime_Time{field: "`search_record_v2`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`search_record_v2`.`updated_at`"},
}

// SearchRecordV2Rels is where relationship names are stored.
var SearchRecordV2Rels = struct {
}{}

// searchRecordV2R is where relationships are stored.
type searchRecordV2R struct {
}

// NewStruct creates a new relationship struct
func (*searchRecordV2R) NewStruct() *searchRecordV2R {
	return &searchRecordV2R{}
}

// searchRecordV2L is where Load methods for each relationship are stored.
type searchRecordV2L struct{}

var (
	searchRecordV2AllColumns            = []string{"id", "member_id", "ipa_id", "name", "version", "created_at", "updated_at"}
	searchRecordV2ColumnsWithoutDefault = []string{"member_id", "ipa_id", "name", "version"}
	searchRecordV2ColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	searchRecordV2PrimaryKeyColumns     = []string{"id"}
)

type (
	// SearchRecordV2Slice is an alias for a slice of pointers to SearchRecordV2.
	// This should almost always be used instead of []SearchRecordV2.
	SearchRecordV2Slice []*SearchRecordV2
	// SearchRecordV2Hook is the signature for custom SearchRecordV2 hook methods
	SearchRecordV2Hook func(context.Context, boil.ContextExecutor, *SearchRecordV2) error

	searchRecordV2Query struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	searchRecordV2Type                 = reflect.TypeOf(&SearchRecordV2{})
	searchRecordV2Mapping              = queries.MakeStructMapping(searchRecordV2Type)
	searchRecordV2PrimaryKeyMapping, _ = queries.BindMapping(searchRecordV2Type, searchRecordV2Mapping, searchRecordV2PrimaryKeyColumns)
	searchRecordV2InsertCacheMut       sync.RWMutex
	searchRecordV2InsertCache          = make(map[string]insertCache)
	searchRecordV2UpdateCacheMut       sync.RWMutex
	searchRecordV2UpdateCache          = make(map[string]updateCache)
	searchRecordV2UpsertCacheMut       sync.RWMutex
	searchRecordV2UpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var searchRecordV2BeforeInsertHooks []SearchRecordV2Hook
var searchRecordV2BeforeUpdateHooks []SearchRecordV2Hook
var searchRecordV2BeforeDeleteHooks []SearchRecordV2Hook
var searchRecordV2BeforeUpsertHooks []SearchRecordV2Hook

var searchRecordV2AfterInsertHooks []SearchRecordV2Hook
var searchRecordV2AfterSelectHooks []SearchRecordV2Hook
var searchRecordV2AfterUpdateHooks []SearchRecordV2Hook
var searchRecordV2AfterDeleteHooks []SearchRecordV2Hook
var searchRecordV2AfterUpsertHooks []SearchRecordV2Hook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SearchRecordV2) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2BeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SearchRecordV2) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2BeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SearchRecordV2) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2BeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SearchRecordV2) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2BeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SearchRecordV2) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2AfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SearchRecordV2) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2AfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SearchRecordV2) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2AfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SearchRecordV2) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2AfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SearchRecordV2) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range searchRecordV2AfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSearchRecordV2Hook registers your hook function for all future operations.
func AddSearchRecordV2Hook(hookPoint boil.HookPoint, searchRecordV2Hook SearchRecordV2Hook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		searchRecordV2BeforeInsertHooks = append(searchRecordV2BeforeInsertHooks, searchRecordV2Hook)
	case boil.BeforeUpdateHook:
		searchRecordV2BeforeUpdateHooks = append(searchRecordV2BeforeUpdateHooks, searchRecordV2Hook)
	case boil.BeforeDeleteHook:
		searchRecordV2BeforeDeleteHooks = append(searchRecordV2BeforeDeleteHooks, searchRecordV2Hook)
	case boil.BeforeUpsertHook:
		searchRecordV2BeforeUpsertHooks = append(searchRecordV2BeforeUpsertHooks, searchRecordV2Hook)
	case boil.AfterInsertHook:
		searchRecordV2AfterInsertHooks = append(searchRecordV2AfterInsertHooks, searchRecordV2Hook)
	case boil.AfterSelectHook:
		searchRecordV2AfterSelectHooks = append(searchRecordV2AfterSelectHooks, searchRecordV2Hook)
	case boil.AfterUpdateHook:
		searchRecordV2AfterUpdateHooks = append(searchRecordV2AfterUpdateHooks, searchRecordV2Hook)
	case boil.AfterDeleteHook:
		searchRecordV2AfterDeleteHooks = append(searchRecordV2AfterDeleteHooks, searchRecordV2Hook)
	case boil.AfterUpsertHook:
		searchRecordV2AfterUpsertHooks = append(searchRecordV2AfterUpsertHooks, searchRecordV2Hook)
	}
}

// One returns a single searchRecordV2 record from the query.
func (q searchRecordV2Query) One(ctx context.Context, exec boil.ContextExecutor) (*SearchRecordV2, error) {
	o := &SearchRecordV2{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for search_record_v2")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SearchRecordV2 records from the query.
func (q searchRecordV2Query) All(ctx context.Context, exec boil.ContextExecutor) (SearchRecordV2Slice, error) {
	var o []*SearchRecordV2

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SearchRecordV2 slice")
	}

	if len(searchRecordV2AfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SearchRecordV2 records in the query.
func (q searchRecordV2Query) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count search_record_v2 rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q searchRecordV2Query) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if search_record_v2 exists")
	}

	return count > 0, nil
}

// SearchRecordV2S retrieves all the records using an executor.
func SearchRecordV2S(mods ...qm.QueryMod) searchRecordV2Query {
	mods = append(mods, qm.From("`search_record_v2`"))
	return searchRecordV2Query{NewQuery(mods...)}
}

// FindSearchRecordV2 retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSearchRecordV2(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*SearchRecordV2, error) {
	searchRecordV2Obj := &SearchRecordV2{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `search_record_v2` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, searchRecordV2Obj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from search_record_v2")
	}

	if err = searchRecordV2Obj.doAfterSelectHooks(ctx, exec); err != nil {
		return searchRecordV2Obj, err
	}

	return searchRecordV2Obj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SearchRecordV2) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no search_record_v2 provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(searchRecordV2ColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	searchRecordV2InsertCacheMut.RLock()
	cache, cached := searchRecordV2InsertCache[key]
	searchRecordV2InsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			searchRecordV2AllColumns,
			searchRecordV2ColumnsWithDefault,
			searchRecordV2ColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(searchRecordV2Type, searchRecordV2Mapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(searchRecordV2Type, searchRecordV2Mapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `search_record_v2` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `search_record_v2` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `search_record_v2` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, searchRecordV2PrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into search_record_v2")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == searchRecordV2Mapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for search_record_v2")
	}

CacheNoHooks:
	if !cached {
		searchRecordV2InsertCacheMut.Lock()
		searchRecordV2InsertCache[key] = cache
		searchRecordV2InsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SearchRecordV2.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SearchRecordV2) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	searchRecordV2UpdateCacheMut.RLock()
	cache, cached := searchRecordV2UpdateCache[key]
	searchRecordV2UpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			searchRecordV2AllColumns,
			searchRecordV2PrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update search_record_v2, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `search_record_v2` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, searchRecordV2PrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(searchRecordV2Type, searchRecordV2Mapping, append(wl, searchRecordV2PrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update search_record_v2 row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for search_record_v2")
	}

	if !cached {
		searchRecordV2UpdateCacheMut.Lock()
		searchRecordV2UpdateCache[key] = cache
		searchRecordV2UpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q searchRecordV2Query) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for search_record_v2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for search_record_v2")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SearchRecordV2Slice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchRecordV2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `search_record_v2` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, searchRecordV2PrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in searchRecordV2 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all searchRecordV2")
	}
	return rowsAff, nil
}

var mySQLSearchRecordV2UniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SearchRecordV2) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no search_record_v2 provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(searchRecordV2ColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSearchRecordV2UniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	searchRecordV2UpsertCacheMut.RLock()
	cache, cached := searchRecordV2UpsertCache[key]
	searchRecordV2UpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			searchRecordV2AllColumns,
			searchRecordV2ColumnsWithDefault,
			searchRecordV2ColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			searchRecordV2AllColumns,
			searchRecordV2PrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert search_record_v2, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`search_record_v2`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `search_record_v2` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(searchRecordV2Type, searchRecordV2Mapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(searchRecordV2Type, searchRecordV2Mapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for search_record_v2")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == searchRecordV2Mapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(searchRecordV2Type, searchRecordV2Mapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for search_record_v2")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for search_record_v2")
	}

CacheNoHooks:
	if !cached {
		searchRecordV2UpsertCacheMut.Lock()
		searchRecordV2UpsertCache[key] = cache
		searchRecordV2UpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SearchRecordV2 record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SearchRecordV2) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SearchRecordV2 provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), searchRecordV2PrimaryKeyMapping)
	sql := "DELETE FROM `search_record_v2` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from search_record_v2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for search_record_v2")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q searchRecordV2Query) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no searchRecordV2Query provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from search_record_v2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for search_record_v2")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SearchRecordV2Slice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(searchRecordV2BeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchRecordV2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `search_record_v2` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, searchRecordV2PrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from searchRecordV2 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for search_record_v2")
	}

	if len(searchRecordV2AfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SearchRecordV2) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSearchRecordV2(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SearchRecordV2Slice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SearchRecordV2Slice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), searchRecordV2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `search_record_v2`.* FROM `search_record_v2` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, searchRecordV2PrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SearchRecordV2Slice")
	}

	*o = slice

	return nil
}

// SearchRecordV2Exists checks if the SearchRecordV2 row exists.
func SearchRecordV2Exists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `search_record_v2` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if search_record_v2 exists")
	}

	return exists, nil
}
