// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package impl

import (
	"context"
	"database/sql"
	"fmt"

	"dumpapp_server/pkg/common/clients"
	"dumpapp_server/pkg/common/errors"
	"dumpapp_server/pkg/dao/models"
	mysqlDriver "github.com/go-sql-driver/mysql"
	pkgErr "github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
)

type MemberIDEncryptionDAO struct {
	mysqlPool *sql.DB
}

var DefaultMemberIDEncryptionDAO *MemberIDEncryptionDAO

func init() {
	DefaultMemberIDEncryptionDAO = NewMemberIDEncryptionDAO()
}

func NewMemberIDEncryptionDAO() *MemberIDEncryptionDAO {
	d := &MemberIDEncryptionDAO{
		mysqlPool: clients.MySQLConnectionsPool,
	}
	return d
}

func (d *MemberIDEncryptionDAO) Insert(ctx context.Context, data *models.MemberIDEncryption) error {
	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}

	err := data.Insert(ctx, exec, boil.Infer())
	if err != nil {
		if mysqlError, ok := pkgErr.Cause(err).(*mysqlDriver.MySQLError); !(ok && mysqlError.Number == 1062) {
			return pkgErr.WithStack(err)
		}
	}
	return nil
}

func (d *MemberIDEncryptionDAO) Update(ctx context.Context, data *models.MemberIDEncryption) error {
	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}
	_, err := data.Update(ctx, exec, boil.Infer())
	return pkgErr.WithStack(err)
}

func (d *MemberIDEncryptionDAO) Delete(ctx context.Context, id int64) error {
	qs := []qm.QueryMod{
		models.MemberIDEncryptionWhere.ID.EQ(id),
	}

	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}
	_, err := models.MemberIDEncryptions(qs...).DeleteAll(ctx, exec)
	if err != nil {
		return pkgErr.WithStack(err)
	}
	return nil
}

func (d *MemberIDEncryptionDAO) Get(ctx context.Context, id int64) (*models.MemberIDEncryption, error) {
	result, err := d.BatchGet(ctx, []int64{id})
	if err != nil {
		return nil, err
	}
	if v, ok := result[id]; !ok {
		return nil, pkgErr.Wrapf(errors.ErrNotFound, "table=member_id_encryption, id=%d", id)
	} else {
		return v, nil
	}
}

// BatchGet retrieves multiple records by primary key from db.
func (d *MemberIDEncryptionDAO) BatchGet(ctx context.Context, ids []int64) (map[int64]*models.MemberIDEncryption, error) {
	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}
	datas, err := models.MemberIDEncryptions(models.MemberIDEncryptionWhere.ID.IN(ids)).All(ctx, exec)
	if err != nil {
		return nil, pkgErr.WithStack(err)
	}

	result := make(map[int64]*models.MemberIDEncryption)
	for _, c := range datas {
		result[c.ID] = c
	}

	return result, nil
}

// 后台和脚本使用：倒序列出所有
func (d *MemberIDEncryptionDAO) ListIDs(ctx context.Context, offset, limit int, filters []qm.QueryMod, orderBys []string) ([]int64, error) {
	if offset < 0 || limit <= 0 || limit > 10000 {
		return nil, pkgErr.Errorf("invalid offset or limit")
	}
	qs := []qm.QueryMod{qm.Select(models.MemberIDEncryptionColumns.ID)}
	qs = append(qs, filters...)

	if len(orderBys) > 0 {
		orderBys = append(orderBys, "id desc")
		for _, orderBy := range orderBys {
			qs = append(qs, qm.OrderBy(orderBy))
		}
	} else {
		qs = append(qs, qm.OrderBy("created_at DESC, id DESC"))
	}

	if offset >= 0 && limit >= 0 {
		qs = append(qs, qm.Offset(offset), qm.Limit(limit))
	}

	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}

	datas, err := models.MemberIDEncryptions(qs...).All(ctx, exec)
	if err != nil {
		return nil, pkgErr.Wrap(err, fmt.Sprintf("table=member_id_encryption offset=%d limit=%d filters=%v", offset, limit, filters))
	}

	result := make([]int64, 0)
	for _, c := range datas {
		result = append(result, c.ID)
	}
	return result, nil
}

func (d *MemberIDEncryptionDAO) Count(ctx context.Context, filters []qm.QueryMod) (int64, error) {
	qs := []qm.QueryMod{qm.Select(models.MemberIDEncryptionColumns.ID)}
	qs = append(qs, filters...)

	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}

	return models.MemberIDEncryptions(qs...).Count(ctx, exec)
}

// GetByCode retrieves a single record by uniq key code from db.
func (d *MemberIDEncryptionDAO) GetByCode(ctx context.Context, code string) (*models.MemberIDEncryption, error) {
	memberIDEncryptionObj := &models.MemberIDEncryption{}

	sel := "*"
	query := fmt.Sprintf(
		"select %s from `member_id_encryption` where `code`=?", sel,
	)

	q := queries.Raw(query, code)

	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}

	err := q.Bind(ctx, exec, memberIDEncryptionObj)
	if err != nil {
		if pkgErr.Cause(err) == sql.ErrNoRows {
			return nil, pkgErr.Wrapf(errors.ErrNotFound, "table=member_id_encryption, query=%s, args=code :%v", query, code)
		}
		return nil, pkgErr.Wrap(err, "dao: unable to select from member_id_encryption")
	}

	return memberIDEncryptionObj, nil
}

// BatchGetByCode retrieves multiple records by uniq key code from db.
func (d *MemberIDEncryptionDAO) BatchGetByCode(ctx context.Context, codes []string) (map[string]*models.MemberIDEncryption, error) {
	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}
	datas, err := models.MemberIDEncryptions(models.MemberIDEncryptionWhere.Code.IN(codes)).All(ctx, exec)
	if err != nil {
		return nil, pkgErr.WithStack(err)
	}

	result := make(map[string]*models.MemberIDEncryption)
	for _, c := range datas {
		result[c.Code] = c
	}

	return result, nil
}

// GetByMemberID retrieves a single record by uniq key memberID from db.
func (d *MemberIDEncryptionDAO) GetByMemberID(ctx context.Context, memberID int64) (*models.MemberIDEncryption, error) {
	memberIDEncryptionObj := &models.MemberIDEncryption{}

	sel := "*"
	query := fmt.Sprintf(
		"select %s from `member_id_encryption` where `member_id`=?", sel,
	)

	q := queries.Raw(query, memberID)

	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}

	err := q.Bind(ctx, exec, memberIDEncryptionObj)
	if err != nil {
		if pkgErr.Cause(err) == sql.ErrNoRows {
			return nil, pkgErr.Wrapf(errors.ErrNotFound, "table=member_id_encryption, query=%s, args=memberID :%v", query, memberID)
		}
		return nil, pkgErr.Wrap(err, "dao: unable to select from member_id_encryption")
	}

	return memberIDEncryptionObj, nil
}

// BatchGetByMemberID retrieves multiple records by uniq key memberID from db.
func (d *MemberIDEncryptionDAO) BatchGetByMemberID(ctx context.Context, memberIDs []int64) (map[int64]*models.MemberIDEncryption, error) {
	var exec boil.ContextExecutor
	txn := ctx.Value("txn")
	if txn == nil {
		exec = d.mysqlPool
	} else {
		exec = txn.(*sql.Tx)
	}
	datas, err := models.MemberIDEncryptions(models.MemberIDEncryptionWhere.MemberID.IN(memberIDs)).All(ctx, exec)
	if err != nil {
		return nil, pkgErr.WithStack(err)
	}

	result := make(map[int64]*models.MemberIDEncryption)
	for _, c := range datas {
		result[c.MemberID] = c
	}

	return result, nil
}
