// Code generated by "enumer -type=MemberVipOrderStatus -json -sql -transform=snake -trimprefix=MemberVipOrderStatus"; DO NOT EDIT.

package enum

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _MemberVipOrderStatusName = "pendingpaid"

var _MemberVipOrderStatusIndex = [...]uint8{0, 7, 11}

const _MemberVipOrderStatusLowerName = "pendingpaid"

func (i MemberVipOrderStatus) String() string {
	i -= 1
	if i < 0 || i >= MemberVipOrderStatus(len(_MemberVipOrderStatusIndex)-1) {
		return fmt.Sprintf("MemberVipOrderStatus(%d)", i+1)
	}
	return _MemberVipOrderStatusName[_MemberVipOrderStatusIndex[i]:_MemberVipOrderStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MemberVipOrderStatusNoOp() {
	var x [1]struct{}
	_ = x[MemberVipOrderStatusPending-(1)]
	_ = x[MemberVipOrderStatusPaid-(2)]
}

var _MemberVipOrderStatusValues = []MemberVipOrderStatus{MemberVipOrderStatusPending, MemberVipOrderStatusPaid}

var _MemberVipOrderStatusNameToValueMap = map[string]MemberVipOrderStatus{
	_MemberVipOrderStatusName[0:7]:       MemberVipOrderStatusPending,
	_MemberVipOrderStatusLowerName[0:7]:  MemberVipOrderStatusPending,
	_MemberVipOrderStatusName[7:11]:      MemberVipOrderStatusPaid,
	_MemberVipOrderStatusLowerName[7:11]: MemberVipOrderStatusPaid,
}

var _MemberVipOrderStatusNames = []string{
	_MemberVipOrderStatusName[0:7],
	_MemberVipOrderStatusName[7:11],
}

// MemberVipOrderStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MemberVipOrderStatusString(s string) (MemberVipOrderStatus, error) {
	if val, ok := _MemberVipOrderStatusNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _MemberVipOrderStatusNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MemberVipOrderStatus values", s)
}

// MemberVipOrderStatusValues returns all values of the enum
func MemberVipOrderStatusValues() []MemberVipOrderStatus {
	return _MemberVipOrderStatusValues
}

// MemberVipOrderStatusStrings returns a slice of all String values of the enum
func MemberVipOrderStatusStrings() []string {
	strs := make([]string, len(_MemberVipOrderStatusNames))
	copy(strs, _MemberVipOrderStatusNames)
	return strs
}

// IsAMemberVipOrderStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MemberVipOrderStatus) IsAMemberVipOrderStatus() bool {
	for _, v := range _MemberVipOrderStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MemberVipOrderStatus
func (i MemberVipOrderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MemberVipOrderStatus
func (i *MemberVipOrderStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MemberVipOrderStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MemberVipOrderStatusString(s)
	return err
}

func (i MemberVipOrderStatus) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *MemberVipOrderStatus) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of MemberVipOrderStatus: %[1]T(%[1]v)", value)
	}

	val, err := MemberVipOrderStatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
